import React from 'react';
import { useParams, Link } from 'react-router-dom';
import { ArrowLeft, ShieldAlert, Cpu, Fingerprint, MapPin, Activity } from 'lucide-react';
import GlassCard from '../components/ui/GlassCard';

const TransactionDetail = () => {
  const { id } = useParams();

  return (
    <div className="space-y-6 max-w-5xl mx-auto">
      <Link to="/transactions" className="flex items-center gap-2 text-sm text-gray-400 hover:text-white transition-colors w-fit">
        <ArrowLeft className="w-4 h-4" /> Back to Intelligence
      </Link>
      
      <div className="flex justify-between items-start">
        <div>
          <h1 className="text-3xl font-bold flex items-center gap-3">
            Transaction Report
            <span className="text-xs px-2 py-1 bg-surface border border-white/10 rounded-full font-mono font-normal">
              {id || 'TXN-9021A'}
            </span>
          </h1>
          <p className="text-gray-400 mt-2">Generated by Neural Engine v2.0</p>
        </div>
        <div className="flex gap-3">
          <button className="px-6 py-2 bg-success/10 text-success border border-success/20 rounded-xl hover:bg-success/20 transition-colors">
            Mark Safe
          </button>
          <button className="px-6 py-2 bg-danger/10 text-danger border border-danger/20 rounded-xl hover:bg-danger/20 transition-colors">
            Block User
          </button>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        <GlassCard className="p-6 md:col-span-2 border-danger/20 bg-gradient-to-br from-surface to-danger/5">
          <div className="flex items-start gap-4">
            <div className="p-4 bg-danger/20 text-danger rounded-xl">
              <ShieldAlert className="w-8 h-8" />
            </div>
            <div>
              <h2 className="text-2xl font-bold text-danger mb-1">98/100 Critical Risk</h2>
              <p className="text-gray-300">Transaction blocked proactively by AI.</p>
            </div>
          </div>
          
          <div className="mt-8 space-y-4">
            <h3 className="font-bold border-b border-white/10 pb-2">AI Reasoning Protocol</h3>
            <div className="bg-background/50 p-4 rounded-xl border border-white/5 space-y-3 font-mono text-sm">
              <p className="text-danger">&gt;{` `} [ALERT] Velocity anomaly detected. 5th transfer to unknown UPI within 10 minutes.</p>
              <p className="text-warning">&gt;{` `} [WARN] Device fingerprint mismatch. Expected iOS 17 (Historical), Found Android Emulator.</p>
              <p className="text-gray-400">&gt;{` `} [INFO] Geolocation check: IP originates from high-risk VPN subnet.</p>
              <p className="text-primary animate-pulse">&gt;{` `} Neural Net Confidence: 99.4% | Rule Engine: MATCH_ATO_PROFILE_V3</p>
            </div>
          </div>
        </GlassCard>

        <div className="space-y-6">
          <GlassCard className="p-6">
            <h3 className="font-bold mb-4 flex items-center gap-2"><Cpu className="w-4 h-4 text-primary"/> AI Scores</h3>
            <div className="space-y-4">
              <div>
                <div className="flex justify-between text-sm mb-1"><span className="text-gray-400">Behavioral Anomaly</span> <span className="text-danger font-bold">95%</span></div>
                <div className="w-full bg-surface h-1.5 rounded-full overflow-hidden"><div className="h-full bg-danger w-[95%]" /></div>
              </div>
              <div>
                <div className="flex justify-between text-sm mb-1"><span className="text-gray-400">Device Spoofing</span> <span className="text-warning font-bold">82%</span></div>
                <div className="w-full bg-surface h-1.5 rounded-full overflow-hidden"><div className="h-full bg-warning w-[82%]" /></div>
              </div>
              <div>
                <div className="flex justify-between text-sm mb-1"><span className="text-gray-400">Network Risk</span> <span className="text-danger font-bold">99%</span></div>
                <div className="w-full bg-surface h-1.5 rounded-full overflow-hidden"><div className="h-full bg-danger w-[99%]" /></div>
              </div>
            </div>
          </GlassCard>

          <GlassCard className="p-6">
             <h3 className="font-bold mb-4 flex items-center gap-2"><Fingerprint className="w-4 h-4 text-secondary"/> Threat Vectors</h3>
             <ul className="space-y-3 text-sm">
               <li className="flex items-center gap-2 text-gray-300"><MapPin className="w-4 h-4 text-gray-500" /> Unknown Location IP</li>
               <li className="flex items-center gap-2 text-gray-300"><Activity className="w-4 h-4 text-gray-500" /> High Velocity Activity</li>
             </ul>
          </GlassCard>
        </div>
      </div>
    </div>
  );
};

export default TransactionDetail;
